[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "target-feature=+simd128",

    "-C",
    "target-feature=+bulk-memory",

    "-C",
    "target-feature=+nontrapping-fptoint",

    "-C",
    "target-feature=+sign-ext",

    "-C",
    "target-feature=+mutable-globals",

]

runner = "node"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C",
    "target-feature=+simd128",

    "-C",
    "target-feature=+bulk-memory",

    "-C",
    "target-feature=+nontrapping-fptoint",

    "-C",
    "target-feature=+sign-ext",

    "-C",
    "target-feature=+mutable-globals",
]
